
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/HLTPerformanceInfo",
  "LCGReflex/std::vector<trigger::TriggerObjectType>",
  "LCGReflex/HLTPerformanceInfo::Path",
  "LCGReflex/std::vector<HLTPerformanceInfo::Path>",
  "LCGReflex/HLTPerformanceInfo::Module",
  "LCGReflex/std::vector<HLTPerformanceInfo::Module>",
  "LCGReflex/trigger::TriggerEventWithRefs",
  "LCGReflex/trigger::TriggerEventWithRefs::TriggerFilterObject",
  "LCGReflex/std::vector<trigger::TriggerEventWithRefs::TriggerFilterObject>",
  "LCGReflex/trigger::TriggerEvent",
  "LCGReflex/trigger::TriggerEvent::TriggerFilterObject",
  "LCGReflex/std::vector<trigger::TriggerEvent::TriggerFilterObject>",
  "LCGReflex/std::vector<edm::Ref<std::vector<reco::PFTau>,reco::PFTau,edm::refhelper::FindUsingAdvance<std::vector<reco::PFTau>,reco::PFTau> > >",
  "LCGReflex/std::vector<edm::Ref<std::vector<reco::RecoChargedCandidate>,reco::RecoChargedCandidate,edm::refhelper::FindUsingAdvance<std::vector<reco::RecoChargedCandidate>,reco::RecoChargedCandidate> > >",
  "LCGReflex/std::vector<edm::Ref<std::vector<reco::Electron>,reco::Electron,edm::refhelper::FindUsingAdvance<std::vector<reco::Electron>,reco::Electron> > >",
  "LCGReflex/std::vector<edm::Ref<std::vector<reco::RecoEcalCandidate>,reco::RecoEcalCandidate,edm::refhelper::FindUsingAdvance<std::vector<reco::RecoEcalCandidate>,reco::RecoEcalCandidate> > >",
  "LCGReflex/edm::ModuleTime",
  "LCGReflex/std::vector<edm::ModuleTime>",
  "LCGReflex/std::map<std::basic_string<char>,std::vector<unsigned int> >",
  "LCGReflex/trigger::TriggerFilterObjectWithRefs",
  "LCGReflex/trigger::TriggerObject",
  "LCGReflex/trigger::HLTPrescaleTable",
  "LCGReflex/trigger::TriggerRefsCollections",
  "LCGReflex/edm::Wrapper<trigger::HLTPrescaleTable>",
  "LCGReflex/edm::Wrapper<trigger::TriggerEventWithRefs>",
  "LCGReflex/edm::Wrapper<trigger::TriggerEvent>",
  "LCGReflex/edm::Wrapper<trigger::TriggerFilterObjectWithRefs>",
  "LCGReflex/edm::Wrapper<HLTPerformanceInfo>",
  "LCGReflex/edm::EventTime",
  "LCGReflex/edm::Wrapper<edm::EventTime>",
  "LCGReflex/reco::HLTResult<24,unsigned short>",
  "LCGReflex/edm::Wrapper<reco::HLTResult<24,unsigned short> >",
  "LCGReflex/reco::HLTResult<16,unsigned short>",
  "LCGReflex/edm::Wrapper<reco::HLTResult<16,unsigned short> >",
  "LCGReflex/reco::HLTResult<8,unsigned short>",
  "LCGReflex/edm::Wrapper<reco::HLTResult<8,unsigned short> >",
  "LCGReflex/std::vector<trigger::TriggerObject>",
  "LCGReflex/__gnu_cxx::__normal_iterator<const trigger::TriggerObjectType*,std::vector<trigger::TriggerObjectType> >",
  "LCGReflex/__gnu_cxx::__normal_iterator<const HLTPerformanceInfo::Path*,std::vector<HLTPerformanceInfo::Path> >",
  "LCGReflex/__gnu_cxx::__normal_iterator<const HLTPerformanceInfo::Module*,std::vector<HLTPerformanceInfo::Module> >",
  "LCGReflex/edm::Wrapper<std::vector<trigger::TriggerObject> >",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

