
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/CaloRecHit",
  "LCGReflex/reco::CaloCluster",
  "LCGReflex/edm::Ptr<reco::CaloCluster>",
  "LCGReflex/std::vector<edm::Ptr<reco::CaloCluster> >",
  "LCGReflex/std::vector<reco::CaloCluster>",
  "LCGReflex/edm::PtrVector<reco::CaloCluster>",
  "LCGReflex/edm::Wrapper<edm::PtrVector<reco::CaloCluster> >",
  "LCGReflex/edm::ValueMap<reco::CaloCluster>",
  "LCGReflex/edm::Wrapper<edm::ValueMap<reco::CaloCluster> >",
  "LCGReflex/edm::Wrapper<std::vector<reco::CaloCluster> >",
  "LCGReflex/edm::RefToBase<CaloRecHit>",
  "LCGReflex/reco::CaloID",
  "LCGReflex/edm::reftobase::BaseHolder<CaloRecHit>",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

