/////////////////////////////////////////////////////////////////////////
//
// 'ORGANIZATION AND SIMULTANEOUS FITS' RooFit tutorial macro #503
// 
// Reading and using a workspace
//
// --> The input file for this macro is generated by rf502_wspaceread.C
// 
//
// 07/2008 - Wouter Verkerke 
//
/////////////////////////////////////////////////////////////////////////
/*
 #ifndef __CINT__
 #include "RooGlobalFunc.h"
 #endif
 #include "RooRealVar.h"
 #include "RooDataSet.h"
 #include "RooGaussian.h"
 #include "RooConstVar.h"
 #include "RooChebychev.h"
 #include "RooAddPdf.h"
 #include "RooWorkspace.h"
 #include "RooPlot.h"
 #include "TCanvas.h"
 #include "TAxis.h"
 #include "TFile.h"
 #include "TH1.h"
 */
using namespace RooFit ;
void getV1Params(int channel, int hilo, double& a1, double& a2, double& a3, double& b1, double& b2, double& b3, double& frac_bkg);

void backgroundFits(int channel = 1, int hilo = 1)
{
	
	gSystem->AddIncludePath("-I$ROOFITSYS/include");
	gROOT->ProcessLine(".L ~/tdrstyle.C");
	setTDRStyle();
	gStyle->SetPadLeftMargin(0.16);
	
	string schannel;
	if (channel == 1) schannel = "4mu";
	else if (channel == 2) schannel = "4e";
	else if (channel == 3) schannel = "2mu2e";
	else std::cout << "Not a valid channel" << std::endl;
	std::cout << "schannel = " << schannel << std::endl;
	string shilo;
	if (hilo == 1) shilo = "lowmass";
	else if (hilo == 2) shilo = "highmass";
	else std::cout << "Not a valid selection" << std::endl;
	
	// R e a d   w o r k s p a c e   f r o m   f i l e
	// -----------------------------------------------
	
	// Open input file with workspace (generated by rf14_wspacewrite)
	char infile[192];
	sprintf(infile,"/scratch/hep/ntran/dataFiles/HZZ4L/datasets/datasets_baseline/%s/ZZAnalysisTree_ZZTo4L_%s.root",schannel.c_str(),shilo.c_str());
	TFile *f = new TFile(infile) ;
	char outfile[192];
	sprintf( outfile, "figs/pdf_%s_bkg_highmass.eps", schannel.c_str() );
	//f->ls();
	
	
	RooDataSet* set = (RooDataSet*) f->Get("data");
	RooArgSet* obs = set->get() ;
	obs->Print();
	RooRealVar* CMS_zz4l_mass = (RooRealVar*) obs->find("CMS_zz4l_mass") ;
	
	for (int i=0 ; i<set->numEntries() ; i++) { 
		set->get(i) ; 
		//cout << CMS_zz4l_mass->getVal() << " = " << set->weight() << endl ; 
	} 
	
	double a11V, a12V, a13V, b11V, b12V, b13V,frac_bkg1V;
	getV1Params(channel, hilo, a11V, a12V, a13V, b11V, b12V, b13V, frac_bkg1V);
	
	gSystem->Load("PDFs/RooZZShape_v1_cxx.so");
	gSystem->Load("PDFs/RooZZShape_v2_cxx.so");
	
	// v1
	RooRealVar a11("a11","a11",a11V,100.,1000.);
	RooRealVar a12("a12","a12",a12V,0,1000.);
	RooRealVar a13("a13","a13",a13V,20.,1000.);
	RooRealVar b11("b11","b11",b11V,100.,1000.);
	RooRealVar b12("b12","b12",b12V,0.,1000.);
	RooRealVar b13("b13","b13",b13V,20.,1000.);
	RooRealVar frac_bkg1("frac_bkg1","frac_bkg1",frac_bkg1V,0.,1.);
	
	//a11.setConstant(kTRUE);
	//a12.setConstant(kTRUE);
	//a13.setConstant(kTRUE);
	//b11.setConstant(kTRUE);
	//b12.setConstant(kTRUE);
	//b13.setConstant(kTRUE);
	//frac_bkg1.setConstant(kTRUE);
	RooZZShape_v1 bkg_qqzz1("bkg_qqzz1","bkg_qqzz1",*CMS_zz4l_mass,a11,a12,a13,b11,b12,b13,frac_bkg1);
	
	// v2
	RooRealVar a1("a1","a1",224.,100.,1000.);
	RooRealVar a2("a2","a2",-209.,-1000.,1000.);
	RooRealVar a3("a3","a3",121.,20.,1000.);
	RooRealVar a4("a4","a4",-0.022,-10.,10.);
	RooRealVar b1("b1","b1",181.,100.,1000.);
	RooRealVar b2("b2","b2",707.,0.,1000.);
	RooRealVar b3("b3","b3",60.,20.,1000.);
	RooRealVar b4("b4","b4",0.04,-10.,10.);
	RooRealVar b5("b5","b5",5.,0.,1000.);
	RooRealVar b6("b6","b6",0.,-10.,10.);
	RooRealVar frac_bkg("frac_bkg","frac_bkg",0.5,0.,1.);
	
	//a1.setConstant(kTRUE);
	//a2.setConstant(kTRUE);
	//a3.setConstant(kTRUE);
	//a4.setConstant(kTRUE);
	//b1.setConstant(kTRUE);
	//b2.setConstant(kTRUE);
	//b3.setConstant(kTRUE);
	//b4.setConstant(kTRUE);
	//b5.setConstant(kTRUE);
	//b6.setConstant(kTRUE);
	frac_bkg.setConstant(kTRUE);
	RooZZShape_v2 bkg_qqzz2("bkg_qqzz2","bkg_qqzz2",*CMS_zz4l_mass,a1,a2,a3,a4,b1,b2,b3,b4,b5,b6,frac_bkg);
	
	RooFitResult *r1 = bkg_qqzz1.fitTo( *set, Save(kTRUE), SumW2Error(kTRUE) );//, Save(kTRUE), SumW2Error(kTRUE)) ;
	//RooFitResult *r2 = bkg_qqzz2.fitTo( *set, Save(kTRUE), SumW2Error(kTRUE) );//, Save(kTRUE), SumW2Error(kTRUE)) ;
	r1->Print();
	
	// Plot Y
	RooPlot* frameM4l = CMS_zz4l_mass->frame(Title("M4L"),Bins(100)) ;
	set->plotOn(frameM4l, MarkerStyle(24)) ;
	bkg_qqzz1.plotOn(frameM4l,LineColor(kRed)) ;
	//bkg_qqzz2.plotOn(frameM4l) ;
	set->plotOn(frameM4l) ;
	
	frameM4l->GetXaxis()->SetTitle("m_{4l} [GeV]");
	frameM4l->GetYaxis()->SetTitle("a.u.");
	
	TCanvas *c = new TCanvas("c","c",800,600);
	c->cd();
	frameM4l->Draw();
	
	char outputName[192];
	sprintf(outputName, "bkgFigs/bkg_%s_%s.eps",schannel.c_str(),shilo.c_str());
	c->SaveAs(outputName);
	
	
}

void getV1Params(int channel, int hilo, double& a1, double& a2, double& a3, double& b1, double& b2, double& b3, double& frac_bkg){
	
	if ((channel == 1)&&(hilo == 1)){
		a1 = 1.23047e+02; a2 = 1.20817e+01; a3 = 1.49462e+02;
		b1 = 1.86593e+02; b2 = 1.06266e+01; b3 = 7.07088e+01;
		frac_bkg = 1.86576e-01;		
	}
	else if ((channel == 2)&&(hilo == 1)){
		a1 = 1.33972e+02; a2 = 1.69651e+01; a3 = 1.49973e+02;
		b1 = 1.86649e+02; b2 = 1.04088e+01; b3 = 6.32582e+01;
		frac_bkg = 2.24786e-01;         		
	}
	else if ((channel == 3)&&(hilo == 1)){
		a1 = 1.32312e+02; a2 = 1.86504e+01; a3 = 1.49995e+02;
		b1 = 1.86223e+02; b2 = 1.10435e+01; b3 = 6.58818e+01;
		frac_bkg = 1.81080e-01;
	}
	else if ((channel == 1)&&(hilo == 2)){
		a1 = 1.62110e+02; a2 = 1.00723e+01; a3 = 1.49963e+02;
		b1 = 1.85660e+02; b2 = 7.52164e+00; b3 = 7.35463e+01;
		frac_bkg = 1.48496e-01;
	}
	else if ((channel == 2)&&(hilo == 2)){
		a1 = 1.99938e+02; a2 = 2.11823e+01; a3 = 1.49984e+02;
		b1 = 1.85964e+02; b2 = 1.10513e+01; b3 = 6.06044e+01;
		frac_bkg = 1.91451e-01;         
	}
	else if ((channel == 3)&&(hilo == 2)){
		a1 = 1.99367e+02; a2 = 2.87184e+01; a3 = 1.04210e+02;
		b1 = 1.87191e+02; b2 = 1.14576e+01; b3 = 4.07366e+01;
		frac_bkg = 4.99031e-01;
	}
	else { 
		std::cout << "DISASTER" << std::endl; 
	}
}
