/********************************************************************
* tmp/slc5_amd64_gcc462/src/ZZMatrixElement/MELA/src/ZZMatrixElementMELA/LinkDef.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/slc5_amd64_gcc462/src/ZZMatrixElement/MELA/src/ZZMatrixElementMELA/LinkDef.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLinkDef();
extern void G__cpp_setup_inheritanceLinkDef();
extern void G__cpp_setup_typetableLinkDef();
extern void G__cpp_setup_memvarLinkDef();
extern void G__cpp_setup_globalLinkDef();
extern void G__cpp_setup_memfuncLinkDef();
extern void G__cpp_setup_funcLinkDef();
extern void G__set_cpp_environmentLinkDef();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LinkDefLN_TClass;
extern G__linked_taginfo G__LinkDefLN_TBuffer;
extern G__linked_taginfo G__LinkDefLN_TMemberInspector;
extern G__linked_taginfo G__LinkDefLN_TObject;
extern G__linked_taginfo G__LinkDefLN_TString;
extern G__linked_taginfo G__LinkDefLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LinkDefLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDefLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LinkDefLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__LinkDefLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LinkDefLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__LinkDefLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__LinkDefLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__LinkDefLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__LinkDefLN_TVar;
extern G__linked_taginfo G__LinkDefLN_TVarcLcLVerbosityLevel;
extern G__linked_taginfo G__LinkDefLN_TVarcLcLMatrixElement;
extern G__linked_taginfo G__LinkDefLN_TVarcLcLProduction;
extern G__linked_taginfo G__LinkDefLN_TVarcLcLProcess;
extern G__linked_taginfo G__LinkDefLN_TVarcLcLLeptonFlavor;
extern G__linked_taginfo G__LinkDefLN_TVarcLcLSuperMelaSyst;
extern G__linked_taginfo G__LinkDefLN_hzz4l_event_type;
extern G__linked_taginfo G__LinkDefLN_mcfm_event_type;
extern G__linked_taginfo G__LinkDefLN_HiggsCSandWidth;
extern G__linked_taginfo G__LinkDefLN_TEvtProb;

/* STUB derived class for protected member access */
