
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin classes
  "LCGReflex/GBRTree",
  "LCGReflex/ElectronLikelihoodCalibration",
  "LCGReflex/ElectronLikelihoodCategoryData",
  "LCGReflex/GBRForest2D",
  "LCGReflex/GBRTree2D",
  "LCGReflex/GBRForest",
  "LCGReflex/ElectronLikelihoodCalibration::Entry",
  "LCGReflex/std::vector<ElectronLikelihoodCalibration::Entry>",
  "LCGReflex/std::vector<GBRTree2D>",
  "LCGReflex/std::vector<GBRTree>",
//--End   classes
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{ 
  names = clnames;
  n = sizeof(clnames)/sizeof(char*);
}

